# Site settings
title: Vince Zipparro
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Vince Zipparro
user_description: As a quality assurnace engineer people might say I'm a problem finder, but I like to think that I'm a problem solver. I'm eager to get involved with new technologies that I am unfamiliar with and like to surround myself with intelligent peers to solve complicated problems. I enjoy working on software that makes the lives of companies, individuals, and the world an easier, better, more connected place. Hopefully, this page gives you a simple summary of where my career has taken me so far as I am eager to exploring new problems, technologies, and projects.
user_title: Quality Assurance Automation Engineer
email: vincezipparro@gmail.com
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
